### ISSUE TITLE
Feature: 启动时自动检查更新

### ISSUE THREAD

**Issue by Chr0n0stasis** [entanex/miraita#19]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

在不必启用命令行的前提下运行bot
并支持自动更新

### 您想要的解决方案

新增一个形如gocq的一键运行脚本，同时在脚本内支持检测最新版本并可选更新至该版本

**Comment by KomoriDev** [comment]
> 新增一个形如gocq的一键运行脚本

一键运行脚本不就是 `pdm run bot.py` ？懒的话可以把这行命令写在 .bat 里
~~什么都一键只会害了你~~
```bash
# run.bat
pdm run bot.py
```
> 在脚本内支持检测最新版本并可选更新至该版本

就是说启动时自动检查更新呗，可以实现。自动更新的话可以尝试使用 `@bot /更新`。
